# Generated by Django 5.0.6 on 2024-07-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todolist_is_default_todolist_is_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='sort_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
