# Generated by Django 5.0.6 on 2024-07-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todotask_sort_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='sort_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
